# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df63a2072a9f2818625ee23d1fc7d3e500e3a26fd5fcb9fa6cdbaded87309d4d5901c8cbb6529e14d1d31313137beb2291bd7fc183144f9b1c710012faeadfc9

test:
  secret_key_base: 1dd82efcc9b1bf82671838a19c4298331b467a15f7f4d3bafee7b99b0c3794286b1631167a4fee68785abd86cb9977f6d628c0ccf61985daad6569e60187c510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
